apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: workload-spot
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
  limits:
    cpu: "100"
    memory: 200Gi
  template:
    metadata:
      labels:
        workload-type: flexible
        capacity-type: spot
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - c7i.2xlarge
            - c8a.2xlarge
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      taints:
        - key: workload-type
          value: flexible
          effect: NoSchedule
